apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: classsync
  labels:
    app: classsync
    component: backend
spec:
  type: ClusterIP
  selector:
    app: classsync
    component: backend
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
